.default-cache: &default-cache
  key: "yarn"
  paths:
    - .yarn-cache/

.pull-cache: &pull-cache
  cache:
    <<: *default-cache
    policy: pull

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - date

after_script:
  - date

test:eslint:
  stage: test
  image: node:8
  <<: *pull-cache
  variables:
    NODE_ENV: test
  script:
    - yarn run eslint
