image: node:8.11.2
clone:
  depth: full
pipelines:
  default:
    - step:
        name: eslint
        caches:
          - node
        script:
          - yarn install
          - yarn run eslint
    - step:
        name: Deploy to Heroku
        deployment: test
        trigger: manual
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
