version: 2
jobs:
  node10:
    docker:
      - image: circleci/node:latest
      - image: mongo
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run coverage

  node8:
    docker:
      - image: circleci/node:carbon
      - image: mongo:3.4.4-jessie
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run coverage

workflows:
  version: 2
  project:
    jobs:
      - node10
      - node8
